### ISSUE TITLE
Corrupted icons with PyQt 5.12

### ISSUE THREAD

**Issue by Adanteh** [spyder-ide/qtawesome#113]
Hey, I had some issues with a corrupted windows profile, and after restoring it for some reason I can't get QtAwesome to show icons anymore. I did do a pip uninstall and install of qtawesome again. Normal QIcon are fine. Not sure on the technical side of this or how it could at all be connected, but I can't figure it out for the life of me. 

![image](https://user-images.githubusercontent.com/1355127/52647784-a3ae2c00-2ee5-11e9-83b2-db1374ae96fc.png)

Icons are being added normally as 
```py
import qtawesome as qta
qta.icon("fa5s.mountain") 
```

**Comment by ccordoba12** [comment]
This is a problem with PyQt5 **5.12** and we don't know how to fix it yet. So please downgrade to 5.11 in the meantime.

**Comment by Adanteh** [comment]
Thanks a lot, that fixed it.

**Comment by stonebig** [comment]
an alternative is to switch to Spyder2 theme, instead of downgrading.

**Comment by ddemidov** [comment]
Can this be reopened until the issue with pyqt 5.12 is resolved?

**Comment by stonebig** [comment]
Pyqt5 mailing list reference: https://www.riverbankcomputing.com/pipermail/pyqt/2019-February/041376.html

**Comment by ddemidov** [comment]
Just a note: if I put some prints into `CharIconEngine.__init__()`, `CharIconEngine.paint()`, and `CharIconEngine.pixmap()` here:

https://github.com/spyder-ide/qtawesome/blob/364d6fd17840cb682e4f8e0df73ccadf7800cb67/qtawesome/iconic_font.py#L145-L163

I can see that `__init__()` is being called, but neither `paint()` nor `pixmap()` are ever entered. Is that normal?

We are using qtawesome in our own project (thanks for the great library btw), so unfortunately switching to Spyder2 theme is not an option.

**Comment by ccordoba12** [comment]
Thanks for digging into this! Did you try it?

@goanpeca, what do you think?

**Comment by ddemidov** [comment]
Just tried on a machine with pyqt 5.11 installed, and I here can see that both `paint` and `pixmap` are called. Here is the patch to `iconic_font.py`:
```diff
diff --git a/qtawesome/iconic_font.py b/qtawesome/iconic_font.py
index 0fb2896..727a557 100644
--- a/qtawesome/iconic_font.py
+++ b/qtawesome/iconic_font.py
@@ -147,16 +147,19 @@ class CharIconEngine(QIconEngine):
     """Specialization of QIconEngine used to draw font-based icons."""
 
     def __init__(self, iconic, painter, options):
+        print('init')
         super(CharIconEngine, self).__init__()
         self.iconic = iconic
         self.painter = painter
         self.options = options
 
     def paint(self, painter, rect, mode, state):
+        print('paint')
         self.painter.paint(
             self.iconic, painter, rect, mode, state, self.options)
 
     def pixmap(self, size, mode, state):
+        print('pixmap')
         pm = QPixmap(size)
         pm.fill(Qt.transparent)
         self.paint(QPainter(pm), QRect(QPoint(0, 0), size), mode, state)
```

I called `example.py` with the patch applied to test this.

**Comment by goanpeca** [comment]
I would need to look deeper into this, I don't recall working on that side, was more @SylvainCorlay I believe :-p

**Comment by ddemidov** [comment]
https://www.riverbankcomputing.com/pipermail/pyqt/2019-March/041459.html
