### ISSUE TITLE
Edit icons style using stylesheet

### ISSUE THREAD

**Issue by upendra-web** [spyder-ide/qtawesome#124]
Hello,

First of all, thanks for the awesome library. 

Is there a way to set an icon's style using stylesheet syntax? because setting a style through python code is not enough in some cases like giving the same style for lot of icons in a list view and change the color of icon only of an active list view item. Thanks in advance.

**Comment by goanpeca** [comment]
>Is there a way to set an icon's style using stylesheet syntax? because setting a style through python code is not enough in some cases like giving the same style for lot of icons in a list view and change the color of icon only of an active list view item. Thanks in advance.

No, there is currently no way to do that! it might require custom parsing of the QSS. Unfortunately Qt does not expose the QSS engine so we would need to parse it from scratch which at the moment is not feasible.
