### ISSUE TITLE
addApplicationFont Locks fonts from reading 

### ISSUE THREAD

**Issue by listyque** [spyder-ide/qtawesome#125]
When app using qtawesome executed another process can't access ttf files to read or delete.

Possible fix:
```
with open(os.path.join(directory, ttf_filename), 'rb') as font_data:
    id_ = QFontDatabase.addApplicationFontFromData(QByteArray(font_data.read()))
font_data.close()

```

**Comment by ccordoba12** [comment]
Please submit a pull request for this. Thanks!

**Comment by listyque** [comment]
Hi. I've been busy last days. Will make PR in a few days. Thanks

**Comment by ccordoba12** [comment]
Great!! Thanks a lot for your help!
