### ISSUE TITLE
Python 3.8: TypeError: 'Shiboken.ObjectType' object is not iterable

### ISSUE THREAD

**Issue by Mingliang2018** [spyder-ide/qtawesome#129]
Hi,
I see the following error while I upgraded python to 3.8 from 3.7.5 recently. Perhaps we need to upgrade QtAwesome as well. I'm using the latest 0.6.0
```python-traceback
mingliang:>py go.py 
Traceback (most recent call last):
  File "go.py", line 3, in <module>
    from central_window import CentralWindowForm, OutLog
  File "/Users/mingliang/Documents/SW_Projects/RFGo/central_window.py", line 9, in <module>
    import qtawesome as qta
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/qtawesome/__init__.py", line 19, in <module>
    from .iconic_font import IconicFont, set_global_defaults
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/qtawesome/iconic_font.py", line 191, in <module>
    class IconicFont(QObject):
**TypeError: 'Shiboken.ObjectType' object is not iterable**
```

**Comment by ccordoba12** [comment]
Are you using PySide2?

**Comment by Mingliang2018** [comment]
Yes, I'm using PySide2 5.13.2 which is updated after Python 3.8 a few days ago.

**Comment by ccordoba12** [comment]
This looks like a compilation error in PySide2 and not our problem really. Please create a simple subclass of `QObject` yourself and try to generate the error.

**Comment by Mingliang2018** [comment]
Hi Ccordoba,
I tried to not used QtAwesome, the issue is gone. So, QtAwesome may need to adapt it. Could you have a try?

**Comment by ccordoba12** [comment]
I'm sorry but we don't have time to do this right now. But you can submit a pull request with a fix, if you want to see this implemented sooner.

**Comment by darkvertex** [comment]
@Mingliang2018 Does importing make it crash or it's upon displaying? Could you paste a short snippet that reproduces the crash for you?

**Comment by Mingliang2018** [comment]
@darkvertex The issue is gone when I updated QtAwesome to the latest version with Python 3.8.1.
