### ISSUE TITLE
Deprecate Python 2 in our CI

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/qtawesome#136]
This issue is to define some timelines on which we will stop support for python 2.7 on CI.

Also at the moment we are testing 2.7, 3.5 and 3.8. Should we update this versions to something else?

Finally we are using conda for these tests, but we could also test with pip only, whcih versions and which systems should we test? I suggest we use Windows and Linux plus Python 3.5 for the pip tests.

Thoughts @ccordoba12 ?

**Comment by ccordoba12** [comment]
> Also at the moment we are testing 2.7, 3.5 and 3.8. Should we update this versions to something else?

Let's release 0.7.0 as the last Python 2 version, then we'll make a 0.x branch for maintenance and release 1.0 with Python 3 support only.

> but we could also test with pip only, whcih versions and which systems should we test?

Tests here are very minimal, so I don't see the need to test things with it.

**Comment by goanpeca** [comment]
>Let's release 0.7.0 as the last Python 2 version, then we'll make a 0.x branch for maintenance and release 1.0 with Python 3 support only.

Sounds good!

**Comment by goanpeca** [comment]
>Tests here are very minimal, so I don't see the need to test things with it.
 
👍

**Comment by listyque** [comment]
> Let's release 0.7.0 as the last Python 2 version, then we'll make a 0.x branch for maintenance and release 1.0 with Python 3 support only.
Why move to py3 exclusively? Is there any real importance for that?

**Comment by goanpeca** [comment]
>Why move to py3 exclusively? Is there any real importance for that?

Yes it is important, it makes maintaining all Spyder projects easier and simpler which allow us to provide better support.

**Comment by ccordoba12** [comment]
> Why move to py3 exclusively? Is there any real importance for that?

Python 2 has reached end-of-line last January 1st, so there's no need to keep maintaining support for it. It's as simple as that.
