### ISSUE TITLE
Replacing qta.icon() with a reference to a variable in another module doesn't work

### ISSUE THREAD

**Issue by Bentroen** [spyder-ide/qtawesome#144]
I'm making an application that uses QtAwesome's icons in two different places: one is the main window, the other is inside a widget that's added later to the same main window.

In an attempt to provide a centralized spot to serve the icons, I created a module called `icons.py`, and inside it, did `import qtawesome as qta` and assigned `qta.icon()` calls to constants:

```
NEW_SONG = qta.icon('mdi.file-plus')
OPEN_SONG = qta.icon('mdi.folder-open')
SAVE_SONG = qta.icon('mdi.content-save')
REWIND = qta.icon('mdi.rewind')
FAST_FORWARD = qta.icon('mdi.fast-forward')
PLAY = qta.icon('mdi.play')
PAUSE = qta.icon('mdi.pause')
...
```

I then imported that module from both places and added references to the constants instead of calling `qta.icon()` directly.

With that done, I start the application, the console shows `UserWarning: You need to have a running QApplication to use QtAwesome!`, and no icons are displayed. I'm fairly certain that the application is already running at that point, since the `icons.py` import (which in turn imports QtAwesome) always happens from the main window, which is always created after the application.

I'm not sure what causes this problem, but it almost looks like the QIcon object is lost in its way across modules. At the same time, my IDE shows that the variables, indeed, refer to QIcon objects:
![image](https://user-images.githubusercontent.com/29354120/80793952-f3baf200-8b6e-11ea-8482-8b8d8af5573b.png)

Intended vs. actual result: 
![image](https://user-images.githubusercontent.com/29354120/80794639-ccfdbb00-8b70-11ea-9619-3983aac12fd0.png)

Is it possible to use QtAwesome in this way?

**Comment by goanpeca** [comment]
Hi @Bentroen thanks for the report.

Because of how qtawesome works it is not possible to use it like you intend to.

Since qta cannot be called without a qapp, this means the module is loading constants and no qapp is available. This is not solved by importing  this after the qapp is created.

You will need to move those calls to a function and then cache the result when the function is called for the first time. Or simply reuse this function call, that could return a dict of icons.

Hope this helps!

**Comment by Bentroen** [comment]
Yeah, I think dicts are the way to go. That's what I was using before, but I thought it'd be smart to move them to a central location instead of keeping them spread over multiple modules.

Just in case I decide to go with the caching route, how would I go about doing that? Would that be efficient at all?
