### ISSUE TITLE
Deprecation warning due to invalid escape sequences 

### ISSUE THREAD

**Issue by tirkarthi** [spyder-ide/qtawesome#147]
Deprecation warnings are raised due to invalid escape sequences. This can be fixed by using raw strings or escaping the literals. pyupgrade also helps in automatic conversion : https://github.com/asottile/pyupgrade/

```
find . -iname '*.py' | grep -v example | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
./qtawesome/icon_browser.py:110: DeprecationWarning: invalid escape sequence \.
  reString += "^%s\." % group
```

**Comment by dalthviz** [comment]
Hi @tirkarthi thanks for the suggestion! Would you like to implement/check the changes that would need to be done? Let us know :)
