### ISSUE TITLE
Implicit integer conversion is deprecated

### ISSUE THREAD

**Issue by juliangilbey** [spyder-ide/qtawesome#162]
I am getting the following warning:

```
  /usr/lib/python3/dist-packages/qtawesome/icon_browser.py:170: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
    self.setGridSize(QtCore.QSize(tileWidth, tileWidth))
```

Adding the line `tileWidth = int(tileWidth)` after setting `iconWidth` on line 168 should fix this:

https://github.com/spyder-ide/qtawesome/blob/b3645859132d097af817455b7dd337c2c002a48c/qtawesome/icon_browser.py#L166-L170

**Comment by dalthviz** [comment]
Hi @juliangilbey thanks for the feedback! Let us know if you want to submit a PR to do the fix :)

**Comment by juliangilbey** [comment]
@dalthviz Done!
