### ISSUE TITLE
qta-browser with PySide6

### ISSUE THREAD

**Issue by kumattau** [spyder-ide/qtawesome#170]
Hi, 
[qtpy](https://github.com/spyder-ide/qtpy) supported PySide6 in master branch.
So I am trying qta-browser with PySide6.

I found some issues and informed them to the corresponding project.

* QtWidegts.QShortcut is missing.
  I sended the pull request to qtpy.
  https://github.com/spyder-ide/qtpy/pull/254

* QFont constructor with family string is broken.
  I reported the problem to PySide6 and I think it will be fixed in future release.
  https://bugreports.qt.io/browse/PYSIDE-1685

But, besides the above, it is left that QApplication.desktop(), which is used in icon_browser.py, is missing.

https://github.com/spyder-ide/qtawesome/blob/a30d520d41d31c23c571ec768eb39bd4df66fdb9/qtawesome/icon_browser.py#L95

About QApplication.desktop(), which component should be fixed ?

**Comment by ccordoba12** [comment]
@kumattau, you're welcome to remove the usage of `QApplication.desktop()` and replace it with `QScreen` instead. We don't have a problem with that.

**Comment by dalthviz** [comment]
@kumattau just in case I merged spyder-ide/qtpy#254 :+1:
