### ISSUE TITLE
Incorrect FontAwesome5 Version in docs and update FontAwesome5 to the latest release (5.15.4)

### ISSUE THREAD

**Issue by kumattau** [spyder-ide/qtawesome#189]
README.md says "FA 5.9.0 features 1,534 free icons in different styles" but FA 5.14.0 seems to be bundled.

I checked the version as follows:

* FA 5.9.0: there are diffs in font and charmap.

```
python setup.py update_fa5 --fa-version 5.9.0
git diff
--- a/qtawesome/fonts/fontawesome5-brands-webfont-charmap.json
+++ b/qtawesome/fonts/fontawesome5-brands-webfont-charmap.json
@@ -48,7 +48,6 @@
     "btc": "f15a",
     "buffer": "f837",
     "buromobelexperte": "f37f",
-    "buy-n-large": "f8a6",
     "buysellads": "f20d",
     "canadian-maple-leaf": "f785",
     "cc-amazon-pay": "f42d",
@@ -73,7 +72,6 @@
     "confluence": "f78d",
     "connectdevelop": "f20e",
     "contao": "f26d",
...
```

* FA 5.14.0: there is diff in font only

```
python setup.py update_fa5 --fa-version 5.14.0
git diff
...
--- a/qtawesome/iconic_font.py
+++ b/qtawesome/iconic_font.py
@@ -33,8 +33,8 @@ SYSTEM_FONTS = False
 # MD5 Hashes for font files bundled with qtawesome:
 MD5_HASHES = {
     'fontawesome4.7-webfont.ttf': 'b06871f281fee6b241d60582ae9369b9',
-    'fontawesome5-regular-webfont.ttf': '808833867034fb67a4a86dd2155e195d',
-    'fontawesome5-solid-webfont.ttf': '139654bb0acaba6b00ae30d5faf3d02f',
+    'fontawesome5-regular-webfont.ttf': '67e860127d1df8f1a3006c83f755fac2',
+    'fontawesome5-solid-webfont.ttf': '1ee101efc765a4068b360a3897f47cd4',
     'fontawesome5-brands-webfont.ttf': '085b1dd8427dbeff10bd55410915a3f6',
     'elusiveicons-webfont.ttf': '207966b04c032d5b873fd595a211582e',
     'materialdesignicons5-webfont.ttf': 'b7d40e7ef80c1d4af6d94902af66e524',
```

Since the timestamp when the family is changed is embedded, the font checksum changes every time the command is executed, which is to be expected.

**Comment by dalthviz** [comment]
Hi @kumattau thanks for the feedback! I think we forgot to update the  README.md` and `usage.rst` to say the new bundled version of FontAwesome (from `5.9.0` to `5.14.0`) when it was update at https://github.com/spyder-ide/qtawesome/pull/151/

Maybe we should update to the latest FontAwesome release: https://github.com/FortAwesome/Font-Awesome/releases/tag/5.15.4

Anyhow, would you like to correct the docs? Let us know!

**Comment by kumattau** [comment]
@dalthviz

OK. I can correct the docs.
I agree it is better to updating FontAwesome to the latest.
FontAwesome's family needs to be changed, but current processing by fonttool is not reproducible (see below).

> Since the timestamp when the family is changed is embedded, the font checksum changes every time the command is executed, which is to be expected.

I think it is better to updating FontAwesome after implementing reproducible processing.
I am working (investigating) for the reproducible processing because the processing is also related to #188.

I will try to work in the following order, but it may take some time. Is there a deadline?

* implement reproducing processing for changing family
* update FontAwesome to the latest
* update docs

**Comment by dalthviz** [comment]
>I will try to work in the following order, but it may take some time. Is there a deadline?
>
>    *  implement reproducing processing for changing family
>    * update FontAwesome to the latest
>    * update docs

That sounds like a good plan to me @kumattau thank you so much for all the help! Regarding a deadline I think we will not be doing more releases this year and probably we will check if a new release is worthy by the end of Jaunary but I don't think that we have an actual deadline for the moment :+1:

**Comment by kumattau** [comment]
> implement reproducing processing for changing family

I sent PR #190

> update FontAwesome to the latest
> update docs

More new FontAwesome may be released, so I'll do the rest before the end of the year.

**Comment by kumattau** [comment]
I found the compatibility breaking changes between 5.14.0 to 5.14.4.
If perform the updates, fa5b.adobe and fa5b.tripadvisor cannot be used.

https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md

> 5.15.3 to 5.15.4
> The tripadvisor brand icon has been removed by legal request of Tripadvisor. 
> 
> 5.14.0 to 5.15.0
> The adobe icon has been removed by legal request of Adobe.

FontAwesome5 cannot be updated from a compatibility standpoint,
but personally I don't see the need to ensure compatibility for icons that Upstream is removing due to legal requirements.

What do you think, @dalthviz  ?

**Comment by dalthviz** [comment]
I'm not totally sure @kumattau . What do you think @ccordoba12 ?

**Comment by ccordoba12** [comment]
> but personally I don't see the need to ensure compatibility for icons that Upstream is removing due to legal requirements.

I don't have a problem with that. Those are only two icons and if people require them in their apps, they can simply pin the QtAwesome version they are using.

**Comment by kumattau** [comment]
Thanks for working on it for me!
