### ISSUE TITLE
Update Codicons to the latest release (0.0.26)

### ISSUE THREAD

**Issue by kumattau** [spyder-ide/qtawesome#191]
README.md says

> msc prefix holds Microsoft's Codicons 0.0.25 with its 385 icons.

but it looks like a working version between 0.0.25 and 0.0.26 is bundled in the package.
I checked that the bundled font and charmap are different from 0.0.25 and 0.0.26.

Now, the latest Codicons 0.0.26 has been released.
So I think that Codicons should be updated to the latest to fix the incorrect version.

**Comment by dalthviz** [comment]
Makes sense to me @kumattau :+1:

**Comment by kumattau** [comment]
I will send the PR before the end of the year.

**Comment by kumattau** [comment]
Thanks for working on it for me!
