### ISSUE TITLE
segmentation fault upon qta.icon()

### ISSUE THREAD

**Issue by grg2rsr** [spyder-ide/qtawesome#21]
I am getting a sementation fault when I try the 

    import qtawesome as qta
    qta.icon('fa.flag')

on both Linux Mint 17 and Ubuntu 14.04

qtawesome was installed via pip and is at version 0.1.7

anything that I missed, or is this a bug?
thanks for help, Georg

**Comment by goanpeca** [comment]
Can you try running the `example.py` file ?

**Comment by grg2rsr** [comment]
yes. Appears to be that the segmentation fault is generated if no qt event loop is running ... thanks for the quick reply!

**Comment by goanpeca** [comment]
So... fixed? should we add something to improve the nonexistent  docs :smile_cat: ?

**Comment by grg2rsr** [comment]
fixed, thank you :)
docs would be nice. I am completely new to icon fonts, and I am browsing around to learn how to use them. Probably there is some central guide/tutorial that I haven't stumbled upon, a link to that would be good for newbies like me.

**Comment by SylvainCorlay** [comment]
Hi @grg2rs, thanks for reporting, indeed, I noticed this as well. Typically one should initialize the QApplication first. There are a couple of API changes that I need to do for integration to Spyder (which should not impact `qta.icon`). Then I will add some sphinx docs.
