### ISSUE TITLE
QtAwesome 1.2.0 incompatybile with PySide2 

### ISSUE THREAD

**Issue by Czaki** [spyder-ide/qtawesome#210]
Thanks for your project, but the last release (1.2.0) brings regression with the PySide2 backend

my tests start failing on the internal QtAwesome import:

```
      from qtpy.QtGui import (QColor, QFont, QFontDatabase, QIcon, QIconEngine,
  E   ImportError: cannot import name 'QGlyphRun' from 'qtpy.QtGui' (/tmp/tox/py310-PySide2-all/lib/python3.10/site-packages/qtpy/QtGui.py)
```
here log:
https://github.com/4DNucleome/PartSeg/actions/runs/3283881224/jobs/5409179903#step:8:49

**Comment by dalthviz** [comment]
Hi @Czaki thanks for the feedback! Indeed seems like PySide2 doesn't have `QGlyphRun` :/ . I think we will need toa add a try-catch to handle this and probably add PySide2 on the CI to prevent incompatibilities in the future :+1:
