### ISSUE TITLE
We should use font-awesome's icons.yml rather than our generated charmap.json

### ISSUE THREAD

**Issue by SylvainCorlay** [spyder-ide/qtawesome#22]
Currently, qtawesome uses a character map that is stored as a .json file for the association 
(icon-name -> unicode character). I generated these files based using yml source available in FontAwesome and Elusive icons.

Font-awesome:   https://github.com/FortAwesome/Font-Awesome/blob/master/src/icons.yml
Elusive icons:  https://github.com/reduxframework/elusive-icons/blob/master/src/icons.yml

Fortunately, they use the same schema in both projects.

To adapt more easily to future versions of FontAwesome and Elusive icons, we should probably directly use those yaml files. However, this would require qtawesome to have a dependency to yml. Unlike json, yml is not part of the Python standard library.

Similarly, I would have to produce a similar file for the spyder font.

**Comment by SylvainCorlay** [comment]
@ccordoba12 any take on that?

**Comment by ccordoba12** [comment]
Let's talk about this in our next week meeting

**Comment by homocomputeris** [comment]
Relevant to the FA's update to v5: [where the new icon names are](https://github.com/FortAwesome/Font-Awesome/issues/12308#issuecomment-365424448)

**Comment by darkvertex** [comment]
Is this still relevant now that FA4 lives in its own namespace away from FA5?

**Comment by pedromorgan** [comment]
Is this still open ??

**Comment by dalthviz** [comment]
Hi, yes! Although seems like it has been open for a while now 🤔 Should we keep this open @ccordoba12 ?

**Comment by ccordoba12** [comment]
We don't have a strong interest to use yml files here. So, perhaps we should close it.
