### ISSUE TITLE
mdi icons not working?

### ISSUE THREAD

**Issue by Dariusz1989** [spyder-ide/qtawesome#221]
Hey

Perhaps I did something wrong.... but I end up with this >
![image](https://user-images.githubusercontent.com/13185728/206795886-d6d6de12-73fc-4981-be30-431acf7782a4.png)
Are they unsupported ? 
I pretty much copied this lib to my project and run directly without setup/etc.
Do I need to setup it up to compile them or something?

**Comment by dalthviz** [comment]
Hi @Dariusz1989 are you by any chance using PySide2? This seems related to https://github.com/spyder-ide/qtawesome/issues/217 and there is not much we can do over the QtAwesome side, sorry :/

**Comment by Dariusz1989** [comment]
Yup its PySide2, can close the thread. darn. Thanks! 
Does Pyside6 work or same issue ? Any ideas?

**Comment by dalthviz** [comment]
> Does Pyside6 work or same issue ? Any ideas?

Checking on Windows, `mdi` works with PySide6 :+1:

>Side question, with that https://github.com/fontello/svg2ttf I take I can re-encode the icons myself ?

Not sure, however seems like that project uses https://github.com/fontello/microbuffer to write the font and it has some options to write into other encodings besides Unicode 32 bits

**Comment by dalthviz** [comment]
Closing this as a duplicate
