### ISSUE TITLE
Update Material Design Icons 6.x (`mdi6`) to latest version (6.9.96)

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/qtawesome#222]
Follow up of https://github.com/spyder-ide/qtawesome/issues/220#issuecomment-1349667091

Update guide (to check if any icon was removed in comparison with the previous version): https://dev.materialdesignicons.com/upgrade

**Comment by StSav012** [comment]
They seem to move the guide to https://pictogrammers.com/docs/library/mdi/releases/upgrade/.
