### ISSUE TITLE
Memory leak when using spin animation class on PyQt bindings

### ISSUE THREAD

**Issue by mgh2010** [spyder-ide/qtawesome#223]
i use the latest version of qtawesome and sampel code.... but its starting to load alots of ram and **at the end it will be crashing like this**:

**gif:**
![vid](https://user-images.githubusercontent.com/55698586/207570103-40d6a599-8189-46bd-9c57-e6ec05674a9d.gif)

**Carashing Error:**
![image](https://user-images.githubusercontent.com/55698586/207569587-608084eb-f548-4b30-acf4-0fa922198e32.png)

**Cod:**

```
import sys
from functools import partial

import qtawesome as qta
from PyQt5.QtWidgets import QApplication, QWidget, QHBoxLayout, QPushButton, QVBoxLayout


class SpinIconTest(QWidget):

    def __init__(self):
        super().__init__()
        self.spin_buttons = list()
        self.setup_ui()

    def setup_ui(self):

        # layout..
        hbox = QHBoxLayout()
        vbox = QVBoxLayout()

        num_buttons = 10

        for i in range(num_buttons):
            button = QPushButton('button {}'.format(i), self)
            vbox.addWidget(button)
            self.spin_buttons.append(button)

        self.button1 = QPushButton('set spin icon!', self)
        self.button1.clicked.connect(partial(self.set_spin_icon))

        self.button2 = QPushButton('set to regular icon!', self)
        self.button2.clicked.connect(partial(self.set_regular_icon))

        hbox.addWidget(self.button1)
        hbox.addWidget(self.button2)

        container_widget = QWidget()
        container_widget.setLayout(vbox)
        hbox.addWidget(container_widget)
        self.setLayout(hbox)

        self.show()

    def set_spin_icon(self):
        for button in self.spin_buttons:
            button.setIcon(qta.icon("fa5s.spinner", animation=qta.Spin(button)))

    def set_regular_icon(self):
        for button in self.spin_buttons:
            button.setIcon(qta.icon("fa5s.check-circle"))


def main():

    app = QApplication([])
    ex = SpinIconTest()

    sys.exit(app.exec_())


if __name__ == '__main__':
    main()
```

**Comment by dalthviz** [comment]
Hi @mgh2010 thank you for the feedback! I was able to reproduce this :+1: We will check it for a future release. In the main time, checking this with PySide2 doesn't show the leaking behavior so you could try using that binding instead of PyQt5

Note: This seems related to the usage of QRawFont on PyQt5 and the cache we use to keep track of QRawFont instances per thread

**Comment by mgh2010** [comment]
hi @dalthviz thank you for the support! my project was build on pyqt5 and its big . so cannot change it to pyside2. i was able to by pass this issue by going back to 1.2.0Ver. i will be happy to look for a future release...
tnx for your support and sorry about my English.

**Comment by dalthviz** [comment]
@mgh2010 could it be possible for you to test if PR #224 helps with the issue (from my local checks it prevents the memory leak but just to be sure)? Let us know!
