### ISSUE TITLE
Wrong default color for disabled state

### ISSUE THREAD

**Issue by maflAT** [spyder-ide/qtawesome#240]
According to the [docs](https://qtawesome.readthedocs.io/en/latest/_generate/qtawesome.icon.html) the default color in disabled state should be grey (150, 150, 150).   
However, it is black by default.  
Manually setting defaults using `
qta.set_defaults(color_disabled=QColor(150, 150, 150))
` works as expected.

**Comment by maflAT** [comment]
This might be a bug in PySide 6.5, using the wrong colors for disabled widgets when dark mode is enabled in Windows.
[https://bugreports.qt.io/browse/QTBUG-114821](https://bugreports.qt.io/browse/QTBUG-114821)

**Comment by dalthviz** [comment]
Thank you @maflAT for the feedback and sorry for the late response! I think the latest versions of PySide6 (6.5.3/6.6.0) should have fixed this (at least from checking the Qt bug report). Let us know if are able to reproduce this with the latest PySide6 bindings!

**Comment by maflAT** [comment]
Yes, it's fixed in the latest PySide release.
