### ISSUE TITLE
Documentation on readthedocs

### ISSUE THREAD

**Issue by SylvainCorlay** [spyder-ide/qtawesome#34]
As per title. We should add the documentation on readthedocs.

**Comment by ghisvail** [comment]
Is the documentation available somewhere in the source tree? I cannot see any on `v0.2.0`.

**Comment by SylvainCorlay** [comment]
@ghisvail it is not at the moment. I started writing the documentation some time ago. What I did is available there: https://github.com/SylvainCorlay/qtawesome/tree/SphinxDoc but was very minimal.

**Comment by ghisvail** [comment]
Thanks for clarifying. The reason I am asking is that I am currently packaging `qtawesome` for Debian as a dependency to spyder 3.x, and needed to know whether a separate documentation package could be built. I will provide it once your PR gets merged and a new release is tagged.

**Comment by SylvainCorlay** [comment]
Awesome! I can push a minimal documentation today or tomorrow so that you have something to point to. I will ping you when it is done.

**Comment by SylvainCorlay** [comment]
I pushed the documentation in master but it does not build yet on readthedocs.

Readthedocs cannot install C extension modules such as PyQt, and these extension modules need to be replaced with mocks.

**Comment by ccordoba12** [comment]
But Qtawesome doesn't depend explictly on PyQt, only Qtpy. And this one doesn't depend on PyQt either :-)

What I mean is that both are pure Python packages.

**Comment by SylvainCorlay** [comment]
Yes, but I cannot import stuff from qtpy if no qt binding is installed.

I was actually looking into shimming qtpy itself instead of PyQt or PySide for the readthedocs doc generation.

**Comment by ccordoba12** [comment]
This is already fixed.
