### ISSUE TITLE
Remove project files from source tree

### ISSUE THREAD

**Issue by ghisvail** [spyder-ide/qtawesome#40]
Please consider removing the `.project` and `.pyproject` currently stored under `qtawesome/`. Those are IDE specific and should not be part of the public source tree.

**Comment by ccordoba12** [comment]
There's no need to remove them. They just need to me moved to the root of the repo, instead of being inside of the `qtawesome` directory.

**Comment by SylvainCorlay** [comment]
I would actually be ok to remove the pydev project from the source tree. I don't use it anymore.
