### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by ghisvail** [spyder-ide/qtawesome#44]
I am currently in the process of packaging `qtawesome` for Debian as it is part of the dependency chain for Spyder 3.x.

Since it is against our packaging policy to embed dependencies, we have to replace the vendored fonts (elusive and fontawesome) by symlinks to the packaged ones. Is there anything else to do on `qtawesome` with regards to the json files then?

**Comment by SylvainCorlay** [comment]
We will probably need to keep these files in the debian package because I generated them for the purpose of this library.

In later versions, we should probably generate this mapping from yaml files provided with these fonts. cf #22.

**Comment by ghisvail** [comment]
> We will probably need to keep these files in the debian package because I generated them for the purpose of this library.

That's ok, the question is whether these should be somehow regenerated or they can be kept as is for now?

**Comment by SylvainCorlay** [comment]
I have the corresponding script in a gist, which is what I used to update font-awesome. Although, this would make qtawesome depend on yaml...

**Comment by SylvainCorlay** [comment]
> > We will probably need to keep these files in the debian package because I generated them for the purpose of this library.
> That's ok, the question is whether these should be somehow regenerated or they can be kept as is for now?

Keeping them for now is probably the simplest way forward. Thanks for working on the Debian packaging!

**Comment by ghisvail** [comment]
All good then. I will submit the package today. Thanks for your assistance.

**Comment by SylvainCorlay** [comment]
@ghisvail awesome. Let me know if there are things that we should improve for the next versions regarding packaging.

For the dependency to font awesome, I was thinking of keeping it in the pip package and wheel but remove it from the source.

A development install would install them from npm...

**Comment by ghisvail** [comment]
Your call. All I am doing right now is just swapping the embedded copy for a symlink. Not that much of an overhead on my end.

One of the co-maintainers of Spyder suggested you guys could use something like `python-xstatic`...?

**Comment by ghisvail** [comment]
Done. We now have both qtpy and qtawesome in Debian. We are closing on the list of dependencies required for Spyder 3.x. Closing.

**Comment by ccordoba12** [comment]
Thanks for your work on this @ghisvail!
