### ISSUE TITLE
setIcon fails with PySide if incorrectly setting QT_API

### ISSUE THREAD

**Issue by ProvoK** [spyder-ide/qtawesome#46]
I had the same problem as in this issue https://github.com/spyder-ide/qtawesome/issues/23
but setting `os.environ['QT_API'] = 'PySide'` did not work for me.
I had to manually uninstall PyQt, but it's not good in terms of portability.
How could i fix that?

**Comment by ccordoba12** [comment]
@ProvoK, could you post a simple code snippet that's giving errors when you have both PyQt and PySide installed, so we can test it in our side? Thanks :-)

We've worked hard to make QtAwesome work with PyQt5, PyQt4 and PySide, but it seems there are some differences between them we haven't addressed correctly :-)

**Comment by ProvoK** [comment]
I'm very sorry for the late reply, i had uninstalled PyQt as "easy fix" since i needed my program running.
I found that the problem was pretty stupid, once i look'd into qtpy code.
It was `os.environ['QT_API'] = 'pyside'` instead `os.environ['QT_API'] = 'PySide'` ...

**Comment by Nodd** [comment]
We should accept the values whatever the letter case. It's just amatter of adding a `.lower()` at the correct place.

**Comment by ProvoK** [comment]
Actually, if i change it to "PySide" it gives me this error
`File "/home/vitto/TESI/PyDaMind/Client/Widgets/Welcome.py", line 9, in <module>
    import qtawesome as qta
  File "/usr/local/lib/python2.7/dist-packages/qtawesome/__init__.py", line 19, in <module>
    from .iconic_font import IconicFont, set_global_defaults
  File "/usr/local/lib/python2.7/dist-packages/qtawesome/iconic_font.py", line 22, in <module>
    from qtpy.QtCore import QObject, QPoint, QRect, qRound, Qt
  File "/usr/local/lib/python2.7/dist-packages/qtpy/__init__.py", line 68, in <module>
    assert os.environ[QT_API] in (PYQT5_API + PYQT4_API + PYSIDE_API)
AssertionError
`

**Comment by ccordoba12** [comment]
@Nodd is right, we should accept values of `QT_API` no matter if they are lower or upper-cased :-)

@ProvoK, we'll fix this one for the next `qtpy` release.

**Comment by ccordoba12** [comment]
This was fixed in qtpy 1.1.2, which is a dependency of qtawesome. Please update to that version.
