### ISSUE TITLE
Support for high-res monitors?

### ISSUE THREAD

**Issue by alexwidener** [spyder-ide/qtawesome#47]
<img width="152" alt="screen shot 2016-05-16 at 10 25 26 pm" src="https://cloud.githubusercontent.com/assets/3489076/15310541/85bdd668-1bb6-11e6-92be-5dcbe0313b7e.png">

That's what the icons look like on a high-res monitor, MacBook Pro Retina.
Currently using PyQt5 and the icons are at a QSize of 32x32.

Curious if there are plans for high-res icon support or if I'm missing something completely? (If I am, forgive me, it's 11 at night here)

**Comment by SylvainCorlay** [comment]
We do support high-res monitors! (Only with PyQt5 though).

What you need to do is enable it at the QApplication level:

```
    app = QtWidgets.QApplication(sys.argv)

    # Enable High DPI display with PyQt5
    if hasattr(QtCore.Qt, 'AA_UseHighDpiPixmaps'):
        app.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps)
```

See our example here:

https://github.com/spyder-ide/qtawesome/blob/master/example.py

**Comment by alexwidener** [comment]
Oh, nice! I just started using PyQt5 two days ago, so I wasn't aware it was something I had to enable. I just tried it out and it looks awesome. 

Thanks a bunch, I'll go ahead and close the issue.
