### ISSUE TITLE
App freezes upon importing qtawesome

### ISSUE THREAD

**Issue by dbeckwith** [spyder-ide/qtawesome#58]
For some reason just importing qtawesome seems to freeze my python script entirely. I can't even stop it with Ctrl+C, I have to use Task Manager to kill it.

The file I'm running is only this:
```python
import sys
from PyQt5.QtWidgets import QApplication
app = QApplication(sys.argv)
import qtawesome as qta
```

[Here](http://pastebin.com/jvuskwY0) is the result of running `python -v testscript.py`. You can see it imports `qtawesome\__init__.py` at line 135, then starts loading a bunch of PyQt modules, then finally freezes at the end on loading `PyQt5.QtWebEngineCore`.

I'm not really sure what to make of this. Let me know if I might be doing something to cause this.

**Comment by ccordoba12** [comment]
Are you using the PyQt 5.7 wheels?

**Comment by dbeckwith** [comment]
I believe so, I just used pip to install it.

**Comment by ccordoba12** [comment]
This is a problem in the PyQt wheels, not a problem with QtAwesome. So there's nothing we can do about it, sorry.
