### ISSUE TITLE
Integration with system fonts

### ISSUE THREAD

**Issue by ghisvail** [spyder-ide/qtawesome#64]
With the new release of QtAwesome v4.x, patching the code to use the system fonts produces a `FontError`, most likely due to a mismatch between the mdf5 sums of the vendored fonts compared to the system ones. Please remember that vendoring is *strongly* discouraged by Linux distributions, hence the need for an integration path.

I would like to discuss with you guys what the best course of actions would be to have `QtAwesome` work with system fonts without complicating the package maintenance burden. Shall, I just make a patch to disable the sum checking part of the code?

**Comment by ccordoba12** [comment]
I think the best solution is for us to add a constant in `qtawesome/__init__.py`, like this

    SYSTEM_FONTS = False

So if this constant is false then we proceed with our hash verification in `iconic_font.py` and if not (e.g. after you patch QtAwesome to make it true) we just skip it.

@ghisvail, what do you think?

**Comment by ghisvail** [comment]
I like that, thanks @ccordoba12

**Comment by ghisvail** [comment]
Do you have a fix I could apply on top of `0.4.1`? I would like to try updating `qtawesome` in Debian before the freeze.

**Comment by ccordoba12** [comment]
When is the freeze?

**Comment by ghisvail** [comment]
Last date for upload should be on the 25th, but sooner would be better.

**Comment by ccordoba12** [comment]
I'll work on this tomorrow.

**Comment by ghisvail** [comment]
Thanks Carlos

**Comment by ghisvail** [comment]
FYI, if all goes well, we should have spyder-3.0.2, qtpy-1.2.0 and qtawesome-0.4.x (0.4.2?) in Debian Stretch.

**Comment by ghisvail** [comment]
I have also started a discussion with the packaging team to check whether we had enough time and resources to package spyder-3.1.0, which you just recently released. Congrats for the release by the way.

**Comment by ghisvail** [comment]
The team is keen on getting spyder-3.1.0 out in Stretch, but we'd have to act fast (we have one downstream using `spyder`, so they'd need some time for testing).

Do you think you can have a version 0.4.1+ of `qtawesome` ready super soon? It does not have to be 0.4.2, just 0.4.1 + a patch applied on my end.

**Comment by ccordoba12** [comment]
I'll release 0.4.2 in a couple of hours.

Also, there are a couple of bugs in Spyder 3.1.0, so we're going to release 3.1.1 in a couple of days, is that ok for you?

**Comment by ghisvail** [comment]
> we're going to release 3.1.1 in a couple of days

Depends what you define by "couple of days"...

> is that ok for you?

We think it is worth the try.

**Comment by ccordoba12** [comment]
> Depends what you define by "couple of days"...

Saturday 21 at most, promised :-)

> We think it is worth the try.

Great!

**Comment by ghisvail** [comment]
> Saturday 21 at most

That should leave us enough time, although the earlier the better.

I am on stand-by for the updates to `qtawesome` and `spyder`.

**Comment by ghisvail** [comment]
@ccordoba12 Any news on the release? I can find some time tomorrow to work on the packaging, after that time will be scarce on my end.

Cheers,
Ghis

**Comment by ccordoba12** [comment]
**0.4.2** is up now :-)
