### ISSUE TITLE
Color on hover

### ISSUE THREAD

**Issue by oriolbv** [spyder-ide/qtawesome#75]
There is a way to change the color of the icon when mouse is over it??

Thanks!

**Comment by foozzi** [comment]
maybe this help for you - mouseMoveEvent ? And after mouse event change color for icon

**Comment by oriolbv** [comment]
I would like not to handle by myself these kind of things, for efficiency reasons. It's not possible to have an option like 'active' but when we hover the button??

Thanks!

**Comment by goanpeca** [comment]
>I would like not to handle by myself these kind of things, for efficiency reasons. It's not possible to have an option like 'active' but when we hover the button??

Nope

Hover is not an Icon state in Qt.

http://doc.qt.io/qt-5/qicon.html

<img width="620" alt="screen shot 2017-07-04 at 08 50 37" src="https://user-images.githubusercontent.com/3627835/27832843-e20e143a-6095-11e7-9757-788e80b0de78.png">
