### ISSUE TITLE
error after build app with pyinstaller

### ISSUE THREAD

**Issue by foozzi** [spyder-ide/qtawesome#78]
```bash
  File "main.py", line 25, in setupUi
    self.play_pause_btn.setIcon(qta.icon('fa.play'))
  File "site-packages/qtawesome/__init__.py", line 125, in icon
  File "site-packages/qtawesome/__init__.py", line 36, in _instance
  File "site-packages/qtawesome/iconic_font.py", line 180, in __init__
  File "site-packages/qtawesome/iconic_font.py", line 223, in load_font
qtawesome.iconic_font.FontError: Font at '/home/foozzi/Projects/yaudio35/src/dist/yaudio/qtawesome/fonts/fontawesome-webfont.ttf' appears to be empty. If you are on Windows 10, please read https://support.microsoft.com/en-us/kb/3053676 to know how to prevent Windows from blocking the fonts that come with QtAwesome.
Failed to execute script yaudio
```

distro: Arch Linux

**Comment by foozzi** [comment]
quick fixed:
just copy ***qtawesome/fonts/*** dir to your dist/ dir after build with ***pyinstaller***

**Comment by ccordoba12** [comment]
Can't you instruct Pyinstaller to copy that file `dist` directly?

**Comment by foozzi** [comment]
do you mean setup.py? or makespec.py?

**Comment by ccordoba12** [comment]
I don't know how Pyinstaller works, but it should be possible to tell how to use/install data files, shouldn't it?

**Comment by foozzi** [comment]
yes PyInstaller can include other files without compiling, but i offered quick solution.

**Comment by ccordoba12** [comment]
Ok, that's good to know. Since what you proposed can be achieved by using Pyinstaller commands, there's no need for us to put a message about it in our Readme.
