### ISSUE TITLE
use pyinstaller to make exe file will raise "Failed to execute script main" problem

### ISSUE THREAD

**Issue by zhqshu** [spyder-ide/qtawesome#80]
It's very easy to use. But when I try to make exe file with pyinstaller, it raises "Failed to execute script main" problem. I found this problem caused by ttf. It seems like blocked by win10. Here is the infomation.
qtawesome.iconic_font.FontError: Font at "\dist\main\qtawesome\fonts\fontawesome-webfont.ttf" appears to be empty. If you are on Windows 10, please read https://support.microsoft.com/en-us/kb/3053676 to know how to proevent Windows from blocking the fonts that come with QtAwesome.

Platform: windows 10 Home
PyInstaller: 3.2.1
Python: 3.4.4

I've tried the method Using Registry Editor, but it makes no difference. so I don't know how to solve this problem.

**Comment by ccordoba12** [comment]
We don't know either, sorry.

**Comment by zhqshu** [comment]
I've figured this out. Add essential files to the spec file and run again. It works! but there is another problem when exe file runs on other new system without the compiling environment, it raises "The version of this file is not compatible with the running windows" problem.

**Comment by zhqshu** [comment]
thanks anyway

**Comment by ccordoba12** [comment]
Sorry but these are Pyinstaller questions, so we can't help you about them.
