### ISSUE TITLE
Can't use hypenated icon names

### ISSUE THREAD

**Issue by Poorchop** [spyder-ide/qtawesome#83]
I've spent the past hour trying to figure out how to use icons with hyphens in the name. For example, I can't use `window-close`. I've tried:
- `fa.window-close`
- `fa.fa-window-close`
- `fa.window_close`
- `fa.windowclose`
- `fa.windowClose`
- `fa-window-close`
- `fa.window.close`

None of the above work, and yes I know that the last two are blatantly wrong and contradict the documentation. All of the examples in the readme only use one-word icon names. `fa.close` works of course, but that's not what I want. I couldn't find any pertinent information on readthedocs either. I do see `window-close` in the charmap file and I highly doubt that icons with hyphenated names haven't been implemented, so I'd really appreciate some help. Thanks.

**Comment by Paloghas** [comment]
I'm having the same problem. 
I'm using qtawesome on Windows 10 (64bit) with Python 3.6.

**Comment by doudz** [comment]
It's works for me on Ubuntu using `fa.window-close`

**Comment by cburgessus** [comment]
It works on my system too. Here are samples of the format I used.
**Solid Icons**
`button_close = QPushButton(qta.icon('fa5s.window-close'),'')`

**Regular Icons**
`button_close = QPushButton(qta.icon('fa5.window-close'),'')`

**Comment by ccordoba12** [comment]
We don't have this problem in Spyder either. Closing then.
