### ISSUE TITLE
Update FontAwesome to its 5 version

### ISSUE THREAD

**Issue by doudz** [spyder-ide/qtawesome#87]
Could you update FA to the last version 5.2.0 ?

**Comment by darkvertex** [comment]
My PR #86 adds support for 5.1.0 but I'm currently blocked by little bug in how the multiple styles are being registered. You're welcome to help me figure it out!

If the little bug goes away I'll be happy to update the PR from 5.1.0 -> 5.2.0

**Comment by doudz** [comment]
I don't know if it's important but, FA5 has 3 styles : solid, regular, light but only solid is free, regular and light are for pro

**Comment by doudz** [comment]
See my fix

**Comment by darkvertex** [comment]
Awesome! I will update my branch to 5.2.0 when I have a bit of time.
